# Fail on error or unbounded variable
set -euo pipefail

# cleanup
rm -rf obj_dir
rm -f lfsr.vcd

# run Verilator to trnanslate Verilog into C++, incuding the C++ testbench
verilator -Wall --cc --trace lfsr.sv --exe lfsr_tb.cpp

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vlfsr.mk Vlfsr

# run exec
obj_dir/Vlfsr
